### ISSUE TITLE
Тест-план api.reputation.ru

### ISSUE THREAD

**Issue by plaksacarp** [plaksacarp/18-12-05-Homework-Lection14#1]
#### Цель
Тестирование API сайта reputation.ru (по ссылке api.reputation.ru). Сайт предназначен для поиска и проверки контрагентов.

#### Тестируемые функции
Тестируются следующие функции сайта:
1. Получение списка контрагентов.
1. Добавление контрагента в список отслеживания.
1. Удаление контрагента из списка отслеживания.
1. Получение списка контрагентов с изменениями.
1. Поиск контрагента по ИНН или ОГРН.

#### Тестовая стратегия и подходы
Будет проведено автоматизированное blackbox позитивное тестирование.
Тестирование проводится со следующими допущениями: данные доступа к сайту предоставлены заказчиком.

#### Расписание
05.12.18 Создать коллекцию тестовых запросов в Postman.
06.12.18 Протестировать коллекцию запросов с использованием Pytest и Request.

#### Критерии начала работ
1. Функционирующий и доступный сайт.
1. Работающий токен доступа к API.

#### Критерии завершения работ
1.	Окончание времени, отведённого на тестирование.
1.	Выполнение всех пунктов запланированного тестирования.
1.	Обнаружение критического дефекта, не позволяющего продолжить работу.
1.	Обстоятельства непреодолимой силы.

#### Риски
1. Время: тестирование будет проведено не в полном объёме.
1. Неработающий токен для доступа к API: невозможно будет провести тестирование.

**Comment by coursar** [comment]
Всё ок. Только Postman - это полуавтоматизированное, или тестирование с элементами автоматизации.
